export const bookData = {
  start_record: 1,
  end_record: 1,
  total_records: 1,
  records: [
    {
      title: "Muqaddimah",
      title_ar: "المقدمة",
      city: {
        city_id: 2,
        city_name: "Damascus",
        city_name_ar: "دمشق",
      },
      collection: {
        collection_id: 1,
        collection_name: "General Collection",
        collection_name_ar: "المجموعة العامة",
      },
      library: {
        library_id: 2,
        city_id: 2,
        library_name: "Al-Assad National Library",
        library_name_ar: "مكتبة الأسد الوطنية",
      },
      subject: {
        subject_id: 1,
        subject: "Islamic Studies",
        subject_ar: "الدراسات الإسلامية",
      },
      author_date: "1377-01-01",
      author_date_hijri: "0779-01-01",
      author_name: "Ibn Khaldun",
      copying_date: "1377-01-01",
      person_roles: [
        {
          person_id: 1,
          person_name: "Ibn Khaldun",
          person_name_ar: "ابن خلدون",
          origin_city_id: null,
          birth_date: "1332-05-27",
          birth_date_hijri: null,
          death_date: "1406-03-17",
          death_date_hijri: null,
          role_id: null,
          role_name: "Author",
          role_name_ar: "مؤلف",
        },
        {
          person_id: 3,
          person_name: "Scribe Ahmed",
          person_name_ar: "الكاتب أحمد",
          origin_city_id: null,
          birth_date: null,
          birth_date_hijri: null,
          death_date: null,
          death_date_hijri: null,
          role_id: null,
          role_name: "Scribe",
          role_name_ar: "كاتب",
        },
      ],
      created_at: "2025-01-24T10:41:54.003724",
      updated_at: "2025-01-24T10:41:54.003724",
    },
  ],
};
